### ISSUE TITLE
Error when missing game ID's

### ISSUE THREAD

**Issue by chessking94** [cmgchess/view-livechesscloud-pgn#4]
This is an awesome tool, thanks for your efforts! I ran into the same "something wrong" error as in #2 when trying to download from tournament bda950bd-7c8d-437c-bde1-da9eed1b6061. I chalked it up to missing game ID's in each round (see no players assigned to game 3 below), as this was the only thing different from the various other tournaments I had downloaded from my source. My workaround was to download each game individually since there weren't that many.

![image](https://github.com/user-attachments/assets/c2017f8a-f680-4e11-8d50-6732cc9e5eb7)

**Comment by cmgchess** [comment]
thanks for reporting the issue! 
this was something i had overlooked

**Comment by cmgchess** [comment]
@chessking94 you can try now. you will still get the empty games as well so will have to deal with those from your end :)

**Comment by chessking94** [comment]
@cmgchess Confirming I was able to download that tournament now, empty games I can handle. Thank you!

**Comment by cmgchess** [comment]
closing
